export const ADD_TASK = 'ADD_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const EDIT_TASK = 'EDIT_TASK';
export const COMPLETE_TASK = 'COMPLETE_TASK';
export const RESTART_TASK = 'RESTART_TASK';
export const COMPLETE_ALL = 'COMPLETE_ALL';
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED';
export const NAVIGATION = '@@router/LOCATION_CHANGE';

export const FETCH_TASK_REQUEST = 'FETCH_TASK_REQUEST';
export const CREATE_TASK_REQUEST = 'CREATE_TASK_REQUEST';
export const DELETE_TASK_REQUEST = 'DELETE_TASK_REQUEST';
export const EDIT_TASK_REQUEST = 'EDIT_TASK_REQUEST';
export const COMPLETE_TASK_REQUEST = 'COMPLETE_TASK_REQUEST';
export const RESTART_TASK_REQUEST = 'RESTART_TASK_REQUEST';

export const FETCH_TASK_RECEIVE = 'FETCH_TASK_RECEIVE';
export const CREATE_TASK_RECEIVE = 'CREATE_TASK_RECEIVE';
export const DELETE_TASK_RECEIVE = 'DELETE_TASK_RECEIVE';

export const TASK_RECEIVE = 'TASK_RECEIVE';

export const FETCH_TASK_ERROR = 'FETCH_TASK_ERROR';
export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR';
// export const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR';
// export const EDIT_TASK_ERROR = 'EDIT_TASK_ERROR';
// export const COMPLETE_TASK_ERROR = 'COMPLETE_TASK_ERROR';
// export const RESTART_TASK_ERROR = 'RESTART_TASK_ERROR';
export const TASK_SET_ERROR = 'TASK_SET_ERROR';
export const TASK_CLEAR_ERROR = 'TASK_CLEAR_ERROR';